/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javapos;

import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajink
 */
public class JavaPos1 extends javax.swing.JFrame {

    private String Eneternumber;
    private JFrame frame;

    /**
     * Creates new form JavaPos1
     */
    public JavaPos1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jtxtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtChange = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jbtnPizza = new javax.swing.JButton();
        jbtnGarlicChickenRice = new javax.swing.JButton();
        jbtnChickenLegPeice = new javax.swing.JButton();
        jbtnManchurian = new javax.swing.JButton();
        jbtnNoodles = new javax.swing.JButton();
        jbtnBurger = new javax.swing.JButton();
        jbtnVegKatthiRolls = new javax.swing.JButton();
        jbtnBiryani = new javax.swing.JButton();
        jbtnIdli = new javax.swing.JButton();
        jbtnVada = new javax.swing.JButton();
        jbtnDosa = new javax.swing.JButton();
        jbtnFriedFish = new javax.swing.JButton();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 140, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tax");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Sub Total");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 40));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 140, 50));

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 140, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 390, 220));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Cash");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Change");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Payment Method");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 50));

        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select method", "Cash", "Visa-Card", "Master-Card" }));
        jPanel5.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 12, 170, 40));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 170, 50));

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 170, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 430, 220));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 380, 40));

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 40));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, 40));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 190, 40));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 190, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 450, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1310, 320));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, 90));

        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 90, 90));

        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, 90));

        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 90));

        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 90, 90));

        jbtnClear.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtnClear.setText("C");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 90, 90));

        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, 90));

        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 90));

        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 90, 90));

        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, 90));

        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 90));

        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 440));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 300, 360));

        jPanel3.setBackground(new java.awt.Color(51, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/pizza.jpeg"))); // NOI18N
        jbtnPizza.setHideActionText(true);
        jbtnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPizzaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 140));

        jbtnGarlicChickenRice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/GingerChick.jpeg"))); // NOI18N
        jbtnGarlicChickenRice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnGarlicChickenRice.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtnGarlicChickenRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGarlicChickenRiceActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnGarlicChickenRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 120));

        jbtnChickenLegPeice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/chickenleg.jpeg"))); // NOI18N
        jbtnChickenLegPeice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnChickenLegPeice.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtnChickenLegPeice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChickenLegPeiceActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnChickenLegPeice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, 120));

        jbtnManchurian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/manchurian.jpeg"))); // NOI18N
        jbtnManchurian.setHideActionText(true);
        jbtnManchurian.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtnManchurian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnManchurianActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnManchurian, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, 120));

        jbtnNoodles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/noodles.jpeg"))); // NOI18N
        jbtnNoodles.setHideActionText(true);
        jbtnNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoodlesActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnNoodles, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 150, 120));

        jbtnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/burger.jpeg"))); // NOI18N
        jbtnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBurgerActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 130));

        jbtnVegKatthiRolls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/roll.jpeg"))); // NOI18N
        jbtnVegKatthiRolls.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnVegKatthiRolls.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnVegKatthiRolls.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtnVegKatthiRolls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVegKatthiRollsActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnVegKatthiRolls, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 160, 130));

        jbtnBiryani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/biryani.jpeg"))); // NOI18N
        jbtnBiryani.setHideActionText(true);
        jbtnBiryani.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtnBiryani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBiryaniActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBiryani, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 140, 130));

        jbtnIdli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/Idli.jpeg"))); // NOI18N
        jbtnIdli.setHideActionText(true);
        jbtnIdli.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtnIdli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIdliActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnIdli, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 150, 130));

        jbtnVada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/vada.jpeg"))); // NOI18N
        jbtnVada.setHideActionText(true);
        jbtnVada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVadaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnVada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 160, 140));

        jbtnDosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/dosa.jpeg"))); // NOI18N
        jbtnDosa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDosaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnDosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 140, 140));

        jbtnFriedFish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapos/fish.jpeg"))); // NOI18N
        jbtnFriedFish.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jbtnFriedFish.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbtnFriedFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFriedFishActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnFriedFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 150, 140));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 670, 440));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DhTt", 1, 48)); // NOI18N
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 300, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//	=============================================Function===========================================
	public void ItemCost() {
	    double sum = 0;
	    double tax = 3.9;
	    
	    for (int i = 0; i < jTable.getRowCount(); i++) {
	        sum = sum + Double.parseDouble(jTable.getValueAt(i, 2).toString());
	    }
	    double cTax = (sum * tax) / 100;
	    String iTaxTotal = String.format("₹ %.2f", cTax);
	    jtxtTax.setText(iTaxTotal);
	    
	    String iSubtotal = String.format("₹ %.2f", sum);
	    jtxtSubTotal.setText(iSubtotal);
	    
	    double cTotal = sum + cTax;
	    String iTotal = String.format("₹ %.2f", cTotal);
	    jtxtTotal.setText(iTotal);
	    
	    String BarCode = String.format("Total is %.2f", cTotal+cTax);
	    jtxtBarCode.setText(BarCode);
	}

	
//	=============================================Function===========================================
	public void Change() {
		double sum = 0;
		double tax = 3.9;
		double cash = Double.parseDouble(jtxtDisplay.getText());

		for (int i = 0; i < jTable.getRowCount(); i++) {
			sum += Double.parseDouble(jTable.getValueAt(i, 2).toString());
		}

		double cTax = (tax * sum) / 100;
		double cChange = cash - (sum + cTax);
		String ChangeGiven = String.format("₹ %.2f", cChange);
		jtxtChange.setText(ChangeGiven);
	}

//	=============================================Function===========================================

    private void jbtnFriedFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFriedFishActionPerformed
      double PriceOfItem=180.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Fried Fish","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnFriedFishActionPerformed

    private void jbtnDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDosaActionPerformed
       double PriceOfItem=80.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Dosa","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnDosaActionPerformed

    private void jbtnVadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVadaActionPerformed
         double PriceOfItem=50.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Vada","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnVadaActionPerformed

    private void jbtnIdliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIdliActionPerformed
       double PriceOfItem=60.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Idli","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnIdliActionPerformed

    private void jbtnBiryaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBiryaniActionPerformed
        double PriceOfItem=160.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Chicken Biryani","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnBiryaniActionPerformed

    private void jbtnVegKatthiRollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVegKatthiRollsActionPerformed
        double PriceOfItem=160.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Veg Katthi Rolls","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnVegKatthiRollsActionPerformed

    private void jbtnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBurgerActionPerformed
       double PriceOfItem=180.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Burger","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnBurgerActionPerformed

    private void jbtnNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoodlesActionPerformed
      double PriceOfItem=80.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Noodles","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnNoodlesActionPerformed

    private void jbtnManchurianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnManchurianActionPerformed
        double PriceOfItem=70.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Manchurian","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnManchurianActionPerformed

    private void jbtnChickenLegPeiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChickenLegPeiceActionPerformed
       double PriceOfItem=160.00;
				DefaultTableModel model =(DefaultTableModel)jTable.getModel();
				model.addRow(new Object[] {"Chicken Leg Peice","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnChickenLegPeiceActionPerformed

    private void jbtnGarlicChickenRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGarlicChickenRiceActionPerformed
       double PriceOfItem = 120;
       
       DefaultTableModel model =(DefaultTableModel) jTable.getModel();
       model.addRow(new Object[] {"Garlic Chicken Rice","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnGarlicChickenRiceActionPerformed

    private void jbtnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPizzaActionPerformed
         double PriceOfItem = 160;
       
       DefaultTableModel model =(DefaultTableModel) jTable.getModel();
       model.addRow(new Object[] {"Pizza","1",PriceOfItem});
				ItemCost();
    }//GEN-LAST:event_jbtnPizzaActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn9.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn9.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn5.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn5.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn6.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn6.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       frame =new JFrame("Exit");
				if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Point of Sale",
						JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION) {
					System.exit(0);
				}
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
       
				if(jcboPayment.getSelectedItem().equals("Cash")) {
					Change();
				} else {
					jtxtChange.setText("");
					jtxtDisplay.setText("");
				}
			
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
       MessageFormat header= new MessageFormat("Printing in Progress");
			MessageFormat footer= new MessageFormat("Page {0, number, integer}");
			
			try {
				jTable.print(JTable.PrintMode.NORMAL,header,footer);
			}catch(java.awt.print.PrinterException ex) {
				System.err.format("No Printer found", ex.getMessage());
			}
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
       DefaultTableModel model =(DefaultTableModel) jTable.getModel();
				int RemoveItem = jTable.getSelectedRow();
				if(RemoveItem >=0) {
					model.removeRow(RemoveItem);
				}
				ItemCost();
				
				if(jcboPayment.getSelectedItem().equals("Cash")) {
					Change();
				}else {
					jtxtChange.setText("");
					jtxtDisplay.setText("");
				}
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtDisplay.setText(null);
				jtxtChange.setText(null);
				jtxtTax.setText(null);
				jtxtSubTotal.setText(null);
				jtxtTotal.setText(null);
				jtxtBarCode.setText(null);
				DefaultTableModel RecordTable = (DefaultTableModel) jTable.getModel();
				RecordTable.setRowCount(0);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
       String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn7.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn7.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn8.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn8.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn4.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn4.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn1.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn1.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn2.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn2.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn3.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn3.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
         String Enternumber = jtxtDisplay.getText();
       if(Eneternumber == ""){
           jtxtDisplay.setText(jbtn0.getText());
       }else{
           Enternumber = jtxtDisplay.getText()+jbtn0.getText();
           jtxtDisplay.setText(Enternumber);
       }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
       if(!jtxtDisplay.getText().contains(".")){
           jtxtDisplay.setText(jtxtDisplay.getText()+ jbtnDot.getText());
       }
    }//GEN-LAST:event_jbtnDotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBiryani;
    private javax.swing.JButton jbtnBurger;
    private javax.swing.JButton jbtnChickenLegPeice;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDosa;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnFriedFish;
    private javax.swing.JButton jbtnGarlicChickenRice;
    private javax.swing.JButton jbtnIdli;
    private javax.swing.JButton jbtnManchurian;
    private javax.swing.JButton jbtnNoodles;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPizza;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnVada;
    private javax.swing.JButton jbtnVegKatthiRolls;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
